apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: hairpin-proxy
spec:
  dnsNames:
    - hogarep.com
  secretName: example-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer