apiVersion: v1
kind: Pod
metadata:
  name: pod-ubuntu
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:20.04
      imagePullPolicy: IfNotPresent
      command: ["/bin/sleep", "365d"]
      volumeMounts:
        - mountPath: /opt
          name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /run/desktop/mnt/host/C/Users/peter/IdeaProjects/kubernetes-apps/podservice/src/main/devops/network-policies/data
        type: DirectoryOrCreate