apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: whatever-mounted-pod
  labels:
    app: whatever-mounted-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /var/www/nginx/custom
          name: pod-vol
  volumes:
    - name: pod-vol
      persistentVolumeClaim:
        claimName: persist-volume-claim-test
  restartPolicy: OnFailure