apiVersion: v1
kind: PersistentVolume
metadata:
  name: persist-volume-test
  labels:
    type: experimental-pv
    category: persistVolume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Mi
  hostPath:
    path: /run/desktop/mnt/host/c/kubernetes-apps/data-pv
    type: DirectoryOrCreate
