apiVersion: v1
kind: Service
metadata:
  name: new-loadbal-svc
spec:
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: echo33
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo33
spec:
  selector:
    matchLabels:
      app: echo33
  replicas: 1
  template:
    metadata:
      labels:
        app: echo33
    spec:
      containers:
        - name: echo1
          image: hashicorp/http-echo
          args:
            - "-text=echo1"
          ports:
            - containerPort: 5678