apiVersion: v1
kind: Service
metadata:
  name: svc-echo-hello
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: echo-hello
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-hello-deploy
spec:
  selector:
    matchLabels:
      app: echo-hello
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-hello
    spec:
      containers:
        - name: echo-svc
          image: hashicorp/http-echo
          args:
            - "-text=Hello World from echo Ingress"
          ports:
            - containerPort: 5678